### ISSUE TITLE
Добавить "избранное"

### ISSUE THREAD

**Issue by mizmo-cheese** [KukikOfficial/CookieOS#1]
Все приложения которые вы запускали раньше будут отображаться на главном экране

**Comment by KukikOfficial** [comment]
хорошая идея но её реализовать не получится ведь игра сапёр была скопирована из интернета и вернутся в ос нельзя к сожалению я не могу это сделать

**Comment by mizmo-cheese** [comment]
> хорошая идея но её реализовать не получится ведь игра сапёр была скопирована из интернета и вернутся в ос нельзя к сожалению я не могу это сделать

Почему? сапер и другое не важно откуда, он тут не причём даже
Можно сделать что при выборе в главном экране OC появилась строка "Недавно запущено" и там было написано то что недавно запустили

**Comment by KukikOfficial** [comment]
У сапёра слишком сложный код и я не могу понять как его перенести прямо во внутрь ос если ты хочешь можешь перенести игры в саму операцинку

**Comment by mizmo-cheese** [comment]
Ладно тогда я сделаю и открою  пулл реквест, окей?

**Comment by KukikOfficial** [comment]
ок

**Comment by mizmo-cheese** [comment]
закрываю, все решено
